# Generated by Django 4.2.7 on 2023-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('nombre_completo_chofer', models.CharField(max_length=50)),
                ('tipo_carga', models.CharField(max_length=100)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
            ],
        ),
    ]
