# Generated by Django 4.2.7 on 2023-11-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(choices=[('1', 'detrito'), ('2', 'bacterias'), ('3', 'plancton'), ('4', 'gusanos'), ('5', 'insectos')], default=1, max_length=50)),
                ('temperatura_almacenamiento', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='camion',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='peso_carga',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='camion',
            name='rut_chofer',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
