# Generated by Django 4.2.7 on 2023-11-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_informecontrolcalidad_camion_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informecontrolcalidad',
            name='tipo_alimento',
            field=models.CharField(choices=[('1', 'detrito'), ('2', 'bacterias'), ('3', 'plancton'), ('4', 'gusanos'), ('5', 'insectos')], default='1', max_length=50),
        ),
    ]
