# Generated by Django 4.2.7 on 2023-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_informecontrolcalidad_tipo_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informecontrolcalidad',
            name='tipo_alimento',
            field=models.CharField(choices=[('1', 'Detrito'), ('2', 'Bacterias'), ('3', 'Plancton'), ('4', 'Gusanos'), ('5', 'Insectos')], default='1', max_length=50),
        ),
    ]
