# Generated by Django 4.2.7 on 2023-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_camion_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='informecontrolcalidad',
            name='tipo_almacenamiento',
            field=models.CharField(choices=[('1', 'Congelados'), ('2', 'Temperatura ambiente'), ('3', 'Helado')], default='1', max_length=50),
        ),
    ]
